### ISSUE TITLE
Call for participation: fix TiDB behaviors for incompatible statements

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#598]
The [event](https://github.com/pingcap/tidb/issues/11486) on improving parser compatibility has been well attended by a lot of contributors, and most of the compatibility issues have been solved.

However, there are statements that are supported __syntactically__ by parser but not __functionally__ by TiDB. To avoid unexpected behaviors in TiDB, we have analyzed each type of statement to decide whether TiDB should throw an error, a warning, or just ignore it.

The final implementation work is assigned to the interested contributors.

Here are some issues: 
- [x] `DATABASE ENCRYPTION`#599 @zhaox1n #717 
- [x] `TABLE ENCRYPTION` #600 @zhaox1n #717
- [x] `CONSTRAINT CHECK` #601 @chanme #888
- [x] `UNION` #602
- [x] `REMOVE PARTITIONING` #603 @wangggong #914 
- [x] `REBUILD/CHECK/OPTIMIZE/REPAIR PARTITION` #604
- [x] `REORGANIZE PARTITION` #605
- [x] `WITH VALIDATION` #606 
- [x] `RENAME COLUMN` #607 @tangenta pingcap/tidb#14281
- [x] `ALTER TABLE ORDER BY` #608 @yuanjize pingcap/tidb#14324
- [x] `TEMPORARY TABLE` #609 @ffutop pingcap/tidb#14452 https://github.com/pingcap/tidb/pull/22860

**Comment by bb7133** [comment]
How about the `TEMPORARY VIEW`?

**Comment by kennytm** [comment]
@bb7133  You could edit the description to add items.

**Comment by morgo** [comment]
> How about the `TEMPORARY VIEW`?

MySQL doesn't support such a feature. It supports global scope or statement-scoped views (aka CTEs) but not session-scoped.
